Control Plane Logging as a default in all patterns
aws-observability/cdk-aws-observability-accelerator pull request #129
Opened 2023-11-06 16:49 UTC by 5herlocked

*Issue #, if available:* #118

*Description of changes:* Added control plane logging through upstream changes and minor modifications to blueprints.
Included documentation changes + instructions on how to access Control Plane logs in CloudWatch.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-07 00:09 UTC, elamaran11 requested changes
@5herlocked Nice work on this PR and blueprints PR. Have some tactical and doc comments. Please fix these when you get chance. We can merge this only after blueprints release so we should also factor for changes to `package.json` later.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-apiserver-observability.md
> +This pattern aims to add Observability and Control plane logging on top of an existing EKS cluster and adds API server monitoring, with open source managed AWS services.
This change is not required. I would rather add a bullet to say. If Control Plane logging is not enabled.. please use enableControlPlane logging function attaching a small relevant code snippet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-awsnative-observability.md
> +This pattern aims to add Observability and control plane logging on top of an existing EKS cluster, with AWS services.
This change is not required. I would rather add a bullet to say. If Control Plane logging is not enabled.. please use enableControlPlane logging function attaching a small relevant code snippet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-mixed-observability.md
> +This pattern aims to add Observability and control plane logging on top of an existing EKS cluster, with a mixture of AWS native and open source managed AWS services.
This change is not required. I would rather add a bullet to say. If Control Plane logging is not enabled.. please use enableControlPlane logging function attaching a small relevant code snippet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-nginx-observability.md
> +This pattern aims to add Observability and control plane logging on top of an existing EKS cluster and NGINX workloads, with open source managed AWS services.
This change is not required. I would rather add a bullet to say. If Control Plane logging is not enabled.. please use enableControlPlane logging function attaching a small relevant code snippet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-opensource-observability.md
> +- Control Plane logging
This change is not required. I would rather add a bullet to say. If Control Plane logging is not enabled.. please use enableControlPlane logging function attaching a small relevant code snippet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-apiserver-opensource-observability.md
> +This pattern demonstrates how to use the _New EKS Cluster Open Source Observability Accelerator_ with API Server monitoring and control plane logging.
Remove, need not required.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-awsnative-fargate-observability.md
> +- Deploys one production grade Amazon EKS Fargate cluster with control plane logging.
Control Plane logging can be sep bullet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-awsnative-observability.md
> +- Deploys one production grade Amazon EKS cluster with control plane logging.
Control Plane logging can be sep bullet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-cluster.md
> +This pattern deploys one production grade Amazon EKS cluster with control plane logging, without any Observability add-on.
remove

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-gpu-opensource-observability.md
> +This pattern deploys an Amazon EKS cluster with control plane logging and a node group that includes instance types featuring NVIDIA GPUs.
Add to end of objective

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-graviton-opensource-observability.md
> +- Deploys one production grade Amazon EKS cluster running on a Graviton3 Processor with control plane logging
Control Plane logging can be sep bullet.

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-java-opensource-observability.md
> +This pattern demonstrates how to use the _New EKS Cluster Open Source Observability Accelerator_ with Java based workloads and control plane logging.
Add to end of objective

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-mixed-observability.md
> +- Deploys one production grade Amazon EKS cluster with Control Plane logging.
Separate item

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-nginx-opensource-observability.md
> +This pattern demonstrates how to use the _New EKS Cluster Open Source Observability Accelerator_ with Nginx based workloads and control plane logging.
Add to end of objective

2023-11-07 00:09 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-opensource-observability.md
> +- Deploys one production grade Amazon EKS cluster with Control Plane logging.
Separate bullet

2023-11-07 00:09 UTC, elamaran11 commented on lib/existing-eks-opensource-observability-pattern/index.ts
> +            .enableControlPlaneLogging()
Remove this has to be optional if not enabled already

2023-11-07 00:09 UTC, elamaran11 commented on lib/existing-eks-mixed-observability-pattern/index.ts
> +            .enableControlPlaneLogging()
Remove this has to be optional if not enabled already

2023-11-07 00:09 UTC, elamaran11 commented on lib/existing-eks-awsnative-observability-pattern/index.ts
> +            .enableControlPlaneLogging()
Remove this has to be optional if not enabled already

2023-11-07 14:20 UTC, elamaran11 requested changes
@5herlocked Looks great, fix these minor issues. We will block the e2e and merge until we have blueprints release.

2023-11-07 14:20 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-apiserver-observability.md
> +!!! note If control plane logging is not enabled in the existing cluster, edit `lib/existing-eks-opensource-observability-pattern/index.ts` to include the following code snippet:
Can we say `to include .enableControlPlaneLogging()  as show below`.

2023-11-07 14:20 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-awsnative-observability.md
> +!!! note If control plane logging is not enabled in the existing cluster, edit `lib/existing-eks-awsnative-observability-pattern/index.ts` to include the following code snippet:
Can we say `to include .enableControlPlaneLogging()  as show below`.

2023-11-07 14:20 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-mixed-observability.md
> +```typescript
Can we say `to include .enableControlPlaneLogging()  as show below`.

2023-11-07 14:20 UTC, elamaran11 commented on docs/patterns/existing-eks-observability-accelerators/existing-eks-nginx-observability.md
> +!!! note If control plane logging is not enabled in the existing cluster, edit `lib/existing-eks-opensource-observability-pattern/index.ts` to include the following code snippet:
Can we say `to include .enableControlPlaneLogging()  as show below`.

2023-12-12 04:20 UTC, 5herlocked commented
Resolved the comments in the docs, ready to GTM after deployment of the upstream changes.

2023-12-19 15:53 UTC, elamaran11 commented
@5herlocked GH Failure needs to be fixed.

2023-12-19 15:54 UTC, 5herlocked commented
Error has nothing to do with my code.

2023-12-19 16:00 UTC, elamaran11 commented
> Error has nothing to do with my code.

This is not because of your code but did you pull from main, that could be the reason. I had one PR yesterday and we never had that error.

2023-12-19 18:49 UTC, elamaran11 commented
/do-e2e-test single-new-eks-awsnative-observability destroy

2023-12-19 19:34 UTC, elamaran11 approved these changes
LGTM

2023-12-19 19:34 UTC, merged