PR - Fargate patterns version upgrade to Kube 1.28
aws-observability/cdk-aws-observability-accelerator pull request #137
Opened 2024-01-03 23:12 UTC by Howlla

*Issue #, if available:* 

*Description of changes:* Remove hardcoded coreDNS version to "auto" and updated fargate cluster provider to kube 1.28

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-03 23:16 UTC, elamaran11 reviewed
@Howlla Thanks for the PR. Have minor comments.

2024-01-03 23:16 UTC, elamaran11 commented on lib/single-new-eks-awsnative-fargate-observability-construct/index.ts
> +            version: eks.KubernetesVersion.of("1.28")
Change this to `auto`. We cant do this for each Kubernetes version to EKS.

2024-01-03 23:16 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/index.ts
> +            version: eks.KubernetesVersion.of("1.28")
Change this to `auto`. We cant do this for each Kubernetes version to EKS.

2024-01-03 23:16 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/index.ts
> +                version: "auto",
this is inaccurate. We dont support auto with individual addons. You have to add the latest supported version,

2024-01-03 23:37 UTC, elamaran11 reviewed
LGTM. Let me run e2e.

2024-01-03 23:38 UTC, elamaran11 commented
/do-e2e-test single-new-eks-awsnative-fargate-observability deploy

2024-01-04 14:00 UTC, elamaran11 commented
/do-e2e-test single-new-eks-awsnative-fargate-observability deploy

2024-01-04 16:26 UTC, elamaran11 commented
/do-e2e-test single-new-eks-awsnative-fargate-observability destroy

2024-01-04 17:31 UTC, elamaran11 commented
/do-e2e-test single-new-eks-fargate-opensource-observability destroy

2024-01-04 17:39 UTC, elamaran11 commented
@Howlla Delete stack is failing with below error. Please fix this

```
single-new-eks-fargate-opensource-observability-accelerator |  53 | 5:35:41 PM | DELETE_FAILED        | AWS::CloudFormation::Stack            | single-new-eks-fargate-opensource-observability-accelerator The following resource(s) failed to delete: [singleneweksfargateopensourceobservabilityacceleratorCoreDnsComputeTypePatchDC03326B].

Failed resources:
single-new-eks-fargate-opensource-observability-accelerator | 5:33:28 PM | DELETE_FAILED        | Custom::AWSCDK-EKS-KubernetesPatch    | single-new-eks-fargate-opensource-observability-accelerator/CoreDnsComputeTypePatch/Resource/Default (singleneweksfargateopensourceobservabilityacceleratorCoreDnsComputeTypePatchDC03326B) Received response status [FAILED] from custom resource. Message returned: Error: b'Error from server (NotFound): deployments.apps "coredns" not found\n'
```

2024-02-03 15:09 UTC, elamaran11 reviewed
@Howlla Impressive work. I think the documentation is not update to date. [This](https://aws-observability.github.io/cdk-aws-observability-accelerator/patterns/single-new-eks-observability-accelerators/single-new-eks-fargate-opensource-observability/#viewing-logs) section is incorrect on logging, we need to update this to what you have done with some screenshots.

2024-02-03 20:20 UTC, Howlla commented
done @elamaran11.

2024-02-03 22:43 UTC, elamaran11 commented
@Howlla Doc Markdown failures, pls fix those.

2024-02-03 22:47 UTC, elamaran11 requested changes
@Howlla Pls fix these

2024-02-03 22:47 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfig.yml
> +        region us-east-1
Why is the region hardcoded, we should pass it as a parameter via YTPL extension

2024-02-03 22:47 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfig.yml
> +        log_group_name fargate-observability
Can we also pass log stream name and group name as inputs too. You can check our AMP Addon for example of using YTPL file.

2024-02-03 22:47 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfigmap.ts
> +export class FluentBitConfigMap implements blueprints.ClusterAddOn {
Can yu add js doc inline in file on what this addon is doing.?

2024-02-03 22:47 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfig.yml
> +kind: Namespace
move this file to common folder under a new sub folder

2024-02-04 20:04 UTC, elamaran11 requested changes
Some convention issues.

2024-02-04 20:04 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfigmap.ts
> +    log_stream_prefix: string;
Use Came case

2024-02-04 20:04 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/fluentbitconfigmap.ts
> +    log_stream_prefix: "from-fluent-bit-",
Use Camelcase

2024-02-04 20:04 UTC, elamaran11 commented on lib/single-new-eks-fargate-opensource-observability-pattern/index.ts
> +            log_stream_prefix: "from-fluent-bit-",
camel case

2024-02-04 21:37 UTC, elamaran11 commented
/do-e2e-test single-new-eks-fargate-opensource-observability deploy

2024-02-04 23:57 UTC, elamaran11 commented
/do-e2e-test single-new-eks-fargate-opensource-observability destroy

2024-02-05 02:13 UTC, elamaran11 commented
Expected Fargate Destroy Failure. Merging the PR.

2024-02-05 02:13 UTC, merged