CDK Istio readme
aws-observability/cdk-aws-observability-accelerator pull request #146
Opened 2024-02-05 14:27 UTC by preddy727

*Issue #, if available:*

*Description of changes:*

CDK Istio readme with bookinfo example and visualization 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-05 16:18 UTC, elamaran11 requested changes
You need to chain this doc to `mkdocs.yaml` file so the doc goes to public website.

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +It also enables control plane logging for comprehensive monitoring on the EKS cluster.
This line can be removed.

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +This pattern demonstrates how to use the _New EKS Cluster Open Source Observability Accelerator_ with Istio based workloads.
Can you talk a little bit about the background what is istio, what is it for monitoring istio and what we are trying to accomplish. You can refer our blogs.

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +      "values": {
Add the missing DASH URLs mandatory as discussed.

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +<img width="1208" alt="image" src="https://github.com/aws-observability/terraform-aws-observability-accelerator/assets/34757337/19b589b4-00f6-465d-a562-1da39e8b9b8c">
Why is this referring to terraform snapshot? Can we have one created in images?

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +<img width="1850" alt="image" src="https://user-images.githubusercontent.com/47993564/236842708-72225322-4f97-44cc-aac0-40a3356e50c6.jpeg">
Can we add these images to this doc images folder and refer it,

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +    To setup your alert receiver, with Amazon SNS, follow [this documentation](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-alertmanager-receiver.html)
Same feedback on screenshot

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +
Could we should screenshot of the Service Dashboard

2024-02-05 16:18 UTC, elamaran11 commented on docs/patterns/single-new-eks-observability-accelerators/single-new-eks-istio-opensource-observability.md
> +Explore the Istio Control Plane, Mesh, and Performance dashboards as well.
Also can you please add screenshots for all the 4 dashboards so people can see it.

2024-02-06 21:12 UTC, preddy727 commented
> You need to chain this doc to `mkdocs.yaml` file so the doc goes to public website.

Mkdocs.yaml link updated.

2024-02-06 21:12 UTC, closed without merging