Changes to pattern folder name to remove construct from it and referencing correct path in .ts files under bin and respective changes in README.md file
aws-observability/cdk-aws-observability-accelerator pull request #91
Opened 2023-08-14 15:31 UTC by naveen-bathula

Changes to pattern folder name to remove construct from it and referencing correct path in .ts files under bin and respective changes in README.md file

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-14 21:44 UTC, elamaran11 requested changes
@naveen-bathula Thankyou for the PR. Could you please rename construct in all lib ts files with pattern than dropping it. Also all class names should have construct replaced with pattern. Also please review two patterns and provide testing screenshots. I prefer AWS Native new cluster and Open source existing cluster make sure to update docs if they are impacted for any names from make command outputs.

2023-08-14 21:44 UTC, elamaran11 commented on bin/existing-eks-awsnative-observability.ts
> +import ExistingEksAwsNativeObservabilityConstruct from '../lib/existing-eks-awsnative-observability';
Why is `ExistingEksAwsNativeObservabilityConstruct` still having `Construct` ? We want to totally get rid of word Construct with `Pattern`. Also we dont want `-construct` to be removed. We would rather want it to be renamed to `-pattern`.

2023-08-14 21:44 UTC, elamaran11 commented on README.md
> -import SingleNewEksOpenSourceobservabilityConstruct from '../lib/single-new-eks-opensource-observability-construct';
Why is `SingleNewEksOpenSourceobservabilityConstruct` still having `Construct` ? We want to totally get rid of word Construct with `Pattern`. Also we dont want `-construct` to be removed. We would rather want it to be renamed to `-pattern`.

2023-08-14 21:44 UTC, elamaran11 commented on bin/existing-eks-mixed-observability.ts
> +import ExistingEksMixedConstruct from '../lib/existing-eks-mixed-observability';
Why is class name `ExistingEksMixedConstruct ` still having `Construct` ? We want to totally get rid of word Construct with `Pattern`. Also we dont want `-construct` to be removed. We would rather want it to be renamed to `-pattern`.

2023-08-14 21:44 UTC, elamaran11 commented on bin/existing-eks-opensource-observability.ts
> +import ExistingEksOpenSourceobservabilityConstruct from '../lib/existing-eks-opensource-observability';
Why is class name `ExistingEksOpenSourceobservabilityConstruct`  still having Construct ? We want to totally get rid of word Construct with Pattern. Also we dont want -construct to be removed. We would rather want it to be renamed to -pattern.

2023-08-14 21:44 UTC, elamaran11 commented on bin/single-new-eks-awsnative-observability.ts
> +import SingleNewEksAWSNativeobservabilityConstruct from '../lib/single-new-eks-awsnative-observability';
Why is class name `SingleNewEksAWSNativeobservabilityConstruct` still having Construct ? We want to totally get rid of word Construct with Pattern. Also we dont want -construct to be removed. We would rather want it to be renamed to -pattern.

2023-08-14 21:44 UTC, elamaran11 commented on bin/single-new-eks-graviton-opensource-observability.ts
> +import SingleNewEksGravitonOpenSourceObservabilityConstruct from '../lib/single-new-eks-opensource-observability/graviton-index';
Why is class name `SingleNewEksGravitonOpenSourceObservabilityConstruct ` still having Construct ? We want to totally get rid of word Construct with Pattern. Also we dont want -construct to be removed. We would rather want it to be renamed to -pattern.

2023-08-14 21:44 UTC, elamaran11 commented on bin/single-new-eks-mixed-observability.ts
> +import SingleNewEksMixedobservabilityConstruct from '../lib/single-new-eks-mixed-observability';
Why is class name `SingleNewEksMixedobservabilityConstruct ` still having Construct ? We want to totally get rid of word Construct with Pattern. Also we dont want -construct to be removed. We would rather want it to be renamed to -pattern.

2023-08-14 21:44 UTC, elamaran11 commented on bin/single-new-eks-opensource-observability.ts
> +import SingleNewEksOpenSourceobservabilityConstruct from '../lib/single-new-eks-opensource-observability';
Why is class name `SingleNewEksOpenSourceobservabilityConstruct ` still having Construct ? We want to totally get rid of word Construct with Pattern. Also we dont want -construct to be removed. We would rather want it to be renamed to -pattern.

2023-08-18 21:47 UTC, naveen-bathula commented
> @naveen-bathula Thankyou for the PR. Could you please rename construct in all lib ts files with pattern than dropping it. Also all class names should have construct replaced with pattern. Also please review two patterns and provide testing screenshots. I prefer AWS Native new cluster and Open source existing cluster make sure to update docs if they are impacted for any names from make command outputs.

@elamaran11 All the requested changes have been made and two suggested patterns were tested and screenshots attached.

![CloudWatch1](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/101e9fd4-456e-44ea-a68c-ef03ec714542)
![CloudWatch2](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/38fad662-dce9-4e72-9253-bab501855232)
![CloudWatch3
![Grafana2](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/2fddef10-91d3-416f-9895-2fbb5cabc960)

![Grafana1](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/c2de34c1-c1e4-42e6-a88f-06b5f2bdf1b4)
](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/6012ff6f-a2c0-451f-916b-77864626c94c)

2023-08-21 22:37 UTC, elamaran11 commented
@shapirov103 Can you quickly check if this is looking good for issue we had.

2023-08-21 22:40 UTC, elamaran11 approved these changes
LGTM.

2023-08-22 13:54 UTC, shapirov103 approved these changes
LGTM

@naveen-bathula I suppose you captured all the doc changes as well. It sounds a bit odd that there ~10 patterns and only two changes in the docs.

2023-08-22 13:55 UTC, shapirov103 commented
@naveen-bathula please address the github action error 
https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91

```
rm -rf dist && node node_modules/.bin/tsc --skipLibCheck
Error: lib/existing-eks-opensource-observability-pattern/index.ts(6[5](https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91#step:7:6),17): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
  Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
Error: lib/single-new-eks-opensource-observability-pattern/graviton-index.ts(49,17): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
  Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
Error: lib/single-new-eks-opensource-observability-pattern/index.ts(51,1[7](https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91#step:7:8)): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
  Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
make: *** [build] Error 2
Error: Process completed with exit code 2.
```

2023-08-22 14:10 UTC, elamaran11 commented
> LGTM
> 
> @naveen-bathula I suppose you captured all the doc changes as well. It sounds a bit odd that there ~10 patterns and only two changes in the docs.

This is because we are not changing the name of the pattern only the file names and class names. @naveen-bathula Please double confirm on Mikhail's feedback.

2023-08-22 14:12 UTC, elamaran11 commented
> @naveen-bathula please address the github action error https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91
> 
> ```
> rm -rf dist && node node_modules/.bin/tsc --skipLibCheck
> Error: lib/existing-eks-opensource-observability-pattern/index.ts(6[5](https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91#step:7:6),17): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
>   Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
> Error: lib/single-new-eks-opensource-observability-pattern/graviton-index.ts(49,17): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
>   Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
> Error: lib/single-new-eks-opensource-observability-pattern/index.ts(51,1[7](https://github.com/aws-observability/cdk-aws-observability-accelerator/actions/runs/5907300979/job/16085531340?pr=91#step:7:8)): error TS2345: Argument of type '{ bootstrapRepo: { repoUrl: string; name: string; targetRevision: string; path: string; }; fluxTargetNamespace: string; bootstrapValues: { AMG_AWS_REGION: string; AMP_ENDPOINT_URL: string; AMG_ENDPOINT_URL: string | undefined; ... 5 more ...; GRAFANA_WORKLOADS_DASH_URL: string; }; }' is not assignable to parameter of type 'FluxCDAddOnProps'.
>   Object literal may only specify known properties, and 'bootstrapRepo' does not exist in type 'FluxCDAddOnProps'.
> make: *** [build] Error 2
> Error: Process completed with exit code 2.
> ```

@naveen-bathula Lets this fix since you are already having an active PR. Check [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/docs/addons/fluxcd.md#single-bootstrap-repo-path) doc for an example to fix it. This is just parameter fix and you can turn it on quickly and just do a quick test. This is because of blueprints flux change breaking the accelerator. Please fix this asap.

2023-08-22 20:39 UTC, elamaran11 requested changes
@naveen-bathula Thankyou for doing this. Some comments. One important change is missing

2023-08-22 20:39 UTC, elamaran11 commented on lib/existing-eks-opensource-observability-pattern/index.ts
> +                        kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure"}]
You are missing `kustomizationTargetNamespace` you should have `            kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure",kustomizationTargetNamespace: "grafana-operator"}]`

2023-08-22 20:39 UTC, elamaran11 commented on lib/single-new-eks-opensource-observability-pattern/graviton-index.ts
> +                        kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure"}]
You are missing kustomizationTargetNamespace you should have             kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure",kustomizationTargetNamespace: "grafana-operator"}]

2023-08-22 20:39 UTC, elamaran11 commented on lib/single-new-eks-opensource-observability-pattern/index.ts
> +                        kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure"}]
You are missing kustomizationTargetNamespace you should have             kustomizations: [{kustomizationPath:"./artifacts/grafana-operator-manifests/eks/infrastructure",kustomizationTargetNamespace: "grafana-operator"}]

2023-08-22 20:39 UTC, elamaran11 commented on package.json
> +  "version": "1.11.0",
this should not change

2023-08-22 20:39 UTC, elamaran11 commented on package.json
>      "@aws-quickstart/eks-blueprints": "^1.10.0",
this should be changed to `"^1.11.0`

2023-08-22 20:39 UTC, elamaran11 commented on package.json
>      "@aws-quickstart/eks-blueprints": "^1.10.0",
this should be changed to `"^1.11.0`

2023-08-22 21:23 UTC, elamaran11 submitted a review, later dismissed
LGTM. Lets show evidence of working grafana boards, so we can merge.

2023-08-23 03:16 UTC, naveen-bathula commented
> LGTM. Please let me know once your e2e is working @naveen-bathula We can merge it.

@elamaran11 

I have tested single-new-eks-opensource-observability and existing-eks-opensource-observability patterns, attached screenshots

![Grafana3](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/162c18e9-0145-471f-b7d3-ab9d994ad8f2)

![Grafana4](https://github.com/aws-observability/cdk-aws-observability-accelerator/assets/32726946/01737767-2b2d-403d-958b-a92a520bbaac)

2023-08-23 10:50 UTC, merged

2023-08-23 10:50 UTC, elamaran11 commented
Nice work @naveen-bathula, Merged.